name: Terraform IAM Role Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instala o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3️⃣ BUILD — inicializa Terraform
      - name: Terraform Init
        run: terraform init

      # 4️⃣ TEST — valida sintaxe
      - name: Terraform Validate
        run: terraform validate

      # 5️⃣ TEST — mostra o plano (simulação)
      - name: Terraform Plan
        run: terraform plan

      # 6️⃣ DEPLOY — aplica na AWS
      - name: Terraform Apply
        run: terraform apply -auto-approve
